[tool.poetry]
name = "talking_keyboard"
version = "0.1.0"
description = "A Raspberry Pi based talking keyboard"
authors = ["Vincent Le Bourlot <vlebourl@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "talking_keyboard" }
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pygame = "^2.5.0"
gTTS = "^2.3.2"
requests = "^2.31.0"
pynput = "^1.7.6"
num2words = "^0.5.12"
evdev = { version = "^1.6.1", markers = "sys_platform == 'linux'" }

[tool.poetry.group.dev.dependencies]
setuptools = "*"
black = "^23.3.0"
isort = "^5.12.0"
ruff = "^0.0.261"
pre-commit = "*"
coverage = "*"

[tool.poetry.scripts]
talking_keyboard = "talking_keyboard.main:main"