COMMON_WORDS_FILE = "common_words.json"
COMMON_LETTERS = "abcdefghijklmnopqrstuvwxyz1234567890"
KEY_MAP = {
    "KEY_A": "q",
    "KEY_B": "b",
    "KEY_C": "c",
    "KEY_D": "d",
    "KEY_E": "e",
    "KEY_F": "f",
    "KEY_G": "g",
    "KEY_H": "h",
    "KEY_I": "i",
    "KEY_J": "j",
    "KEY_K": "k",
    "KEY_L": "l",
    "KEY_N": "n",
    "KEY_O": "o",
    "KEY_P": "p",
    "KEY_Q": "a",
    "KEY_R": "r",
    "KEY_S": "s",
    "KEY_T": "t",
    "KEY_U": "u",
    "KEY_V": "v",
    "KEY_W": "z",
    "KEY_X": "x",
    "KEY_Y": "y",
    "KEY_Z": "w",
    "KEY_0": "0",
    "KEY_1": "1",
    "KEY_2": "2",
    "KEY_3": "3",
    "KEY_4": "4",
    "KEY_5": "5",
    "KEY_6": "6",
    "KEY_7": "7",
    "KEY_8": "8",
    "KEY_9": "9",
    "KEY_SEMICOLON": "m",
    "KEY_SPACE": " ",
    "KEY_ENTER": "\n",
    "KEY_BACKSPACE": "\b",
    "KEY_TAB": "\t",
    "KEY_KPENTER": "\n",
    "KEY_KP0": "0",
    "KEY_KP1": "1",
    "KEY_KP2": "2",
    "KEY_KP3": "3",
    "KEY_KP4": "4",
    "KEY_KP5": "5",
    "KEY_KP6": "6",
    "KEY_KP7": "7",
    "KEY_KP8": "8",
    "KEY_KP9": "9",
    # Add other keys as needed
}
MP3_DIR = "sounds"
