name: Test and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libasound2-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run -m unittest test_main.py

    - name: Report coverage
      run: |
        coverage report -m

    - name: Generate and upload HTML coverage report
      run: |
        coverage html
      uses: actions/upload-artifact@v2
      with:
        name: coverage-html
        path: htmlcov/
