name: Lint and Validate

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Lint with flake8
        run: pipenv run flake8

      - name: Check typing with mypy
        run: pipenv run mypy

      - name: Check formatting with black
        run: pipenv run black --check .

      - name: Check imports with isort
        run: pipenv run isort --check --diff .
